import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import RLCLogo from '../public/RLC.png';
import landscape from '../public/landscape.png';
import ITS from '../public/moving.png';
import ITC from '../public/more.png';
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import {useState} from "react";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>ReyesLC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className=' bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-center text-2xl font-burtons'>Orlie Reyes</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill 
                onClick={() => setDarkMode(!darkMode)} 
                className="cursor-pointer text-2xl dark:text-white"/>
              </li>
            </ul>
          </nav>

          <div className="text-center"> 
          <div className= "relative mx-auto bg-gradient-to-t from-green-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={RLCLogo}/>
          </div>
            <h3 className="text-3xl">Services</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto'>
            "Welcome to our landscaping company! We offer a wide range of services including mowing, weed eating, tree trimming, leaf blowing and haul-offs. Our experienced team will create a customized plan for you. Contact us today to schedule your next service and let us take care of your lawn care needs!
            </p>
          </div>

          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className="mx-auto"src={landscape} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Lawn Care
              </h3>
              <p className="py-2">
              We will ensure top-notch maintenance for your lawn by utilizing effective communication, suitable equipment, and skilled professionals.
              </p>
              <h4 className="py-4 text-teal-600">Specific Services Offered:</h4>
              <p className="text-gray-800 py-1">Mowing</p>
              <p className="text-gray-800 py-1">Weed Eating</p>
              <p className="text-gray-800 py-1">Tree Trimming</p>
              <p className="text-gray-800 py-1">Blowing</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className="mx-auto"src={ITS} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Haul-Off's
              </h3>
              <p className="py-2">
                INSERT BRIEF DESCRIPTION HERE
              </p>
              <h4 className="py-4 text-teal-600">INCLUDING</h4>
              <p className="text-gray-800 py-1">EXAMPLE</p>
              <p className="text-gray-800 py-1">EXAMPLE</p>
              <p className="text-gray-800 py-1">EXAMPLE</p>
              <p className="text-gray-800 py-1">EXAMPLE</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image className="mx-auto"src={ITC} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                And Much More!
              </h3>
              <p className="py-2">
                We are open to all sort of work please give us a call extra hand.
              </p>
              
            </div>
          </div>

        </section>
        
        
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint accusamus, saepe architecto repudiandae, ut repellendus quis dolorem minima, magni at quidem. Dicta necessitatibus ad corporis veritatis deserunt cupiditate voluptates pariatur?
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>

      </main>
    </div>
  )
}


